# Align Analysis

Input 파일에서 `answer_matches_gold` 와 `align` 두 열의 분포를 테이블로 확인합니다.

In [1]:
from pathlib import Path
import json
import pandas as pd

def align_table(input_path):
    with input_path.open("r", encoding="utf-8") as f:
        records = json.load(f)

    df = pd.DataFrame(records)
    df[["answer_matches_gold", "align"]].head()
    answer_group = df["answer_matches_gold"].map(lambda x: "true" if x is True else "false")

    table = pd.crosstab(
        answer_group,
        df["align"].fillna("null").astype(str),
        dropna=False,
    )
    table.index.name = "answer"
    table.columns.name = "align"

    table_with_total = table.copy()
    table_with_total["total"] = table_with_total.sum(axis=1)
    table_with_total.loc["total"] = table_with_total.sum(axis=0)
    return table_with_total

#### open-book

In [62]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0410/2wiki_vanilla_vs_triplet.json"))

align    no  yes  total
answer
false   138  169    307
true     51  142    193
total   189  311    500

In [63]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0410/hotpotqa_vanilla_vs_triplet.json"))

align    no  yes  total
answer
false    98  132    230
true     61  209    270
total   159  341    500

In [64]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0410/musique_vanilla_vs_triplet.json"))

align    no  yes  total
answer
false   413  483    896
true     26   78    104
total   439  561   1000

#### open-book + gold

In [65]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0410/2wiki_vanilla_vs_triplet_openbook+gold.json"))

align    no  yes  total
answer
false   143  164    307
true     57  136    193
total   200  300    500

In [66]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0410/hotpotqa_vanilla_vs_triplet_openbook+gold.json"))

align    no  yes  total
answer
false    96  134    230
true     60  210    270
total   156  344    500

In [67]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0410/musique_vanilla_vs_triplet_openbook+gold.json"))

align    no  yes  total
answer
false   414  482    896
true     22   82    104
total   436  564   1000

### vanilla subquery vs. triplet

In [2]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0413/2wiki_vanilla_vs_triplet_subquery_openbook.json"))

align    no  yes  total
answer
false    76  231    307
true     43  150    193
total   119  381    500

In [6]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0413/musique_vanilla_vs_triplet_subquery_openbook.json"))

align    no  yes  total
answer
false   286  610    896
true     25   79    104
total   311  689   1000

In [5]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0413/hotpotqa_vanilla_vs_triplet_subquery_openbook.json"))

align    no  yes  total
answer
false    63  167    230
true     74  196    270
total   137  363    500

### vanilla subquery + think vs. triplet

In [2]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0416/2wiki_vanilla_vs_triplet_think+subquery_openbook.json"))

align    no  yes  total
answer
false   111  196    307
true     32  161    193
total   143  357    500

In [3]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0416/musique_vanilla_vs_triplet_think+subquery_openbook.json"))

align    no  yes  total
answer
false   386  510    896
true     23   81    104
total   409  591   1000

In [4]:
align_table(Path("/home/hyeseojeon/data/graph/results/analysis/0416/hotpotqa_vanilla_vs_triplet_think+subquery_openbook.json"))

align    no  yes  total
answer
false    92  138    230
true     44  226    270
total   136  364    500